# This is the default configuration file for conman.

images:
    root:
        generate: false
        name: "root_img_name"
        tag: "root_img_tag"
        from_image:
            name: "ubuntu"
            tag: "20.04"
        conda_environment:
            enabled: true
            directory: "/opt/conda"
            env_name: "myenv"
            environment_file: "./environment.yml"
        extra_instructions: [] # Add extra arguments to docker build command "INSTRUCTION [ARGUMENTS]" classically add root specific instructions

    user:
        extra_instructions: [] # Add extra arguments to docker build command "INSTRUCTION [ARGUMENTS]", classically add user specific instructions (don't sudo if needed)

user_settings:
    volumes: [] # Use docker compose volumes syntaxe <path_host>:<path_container>

container:
    name: "compose_img_name"
    main_service:
        name: "main_container"
        container_name: "container_stack_name"

    devcontainer:
        enabled: true
        name: "devcontainer_name"
        extensions: []

    graphical:
        enabled: false
        protocol: "x11"

    gpu:
        enabled: false
        manufacturer: "nvidia"
        count: 1
