# This is the default configuration file for conman.

root_image:
    generate: false
    name: "your_image_name"
    tag: "your_image_tag"
    conda:
        enabled: true
        directory: "/opt/conda"
        env_name: "myenv"
        environment_file: "environment.yml"

volumes: []

graphical:
    enabled: false
    protocol: "x11"

gpu:
    enabled: false
    manufacturer: "nvidia"
    count: 0

container:
    name: "compose_img_name"
    main_service:
        name: "main_container"
        container_name: "your_container_name"
    devcontainer:
        enabled: true
        name: "your_devcontainer_name"
        extensions: []
